[general]
cache = "~/.cache"

[language]
ui = "hu"
prompt = "hu"

[models]
general = "qwen3.5:9B"
translation = ""
vision = ""

[openai]
api_base = "http://10.6.6.20:11434/v1"
api_key = "not-needed"
keep_alive = "30m"
enable_thinking = false
thinking_budget = 1024
max_output_tokens = 1536
translation_max_output_tokens = 2048
prompt_temperature = 0.9
prompt_frequency_penalty = 1.5

[tts]
# TTS protocol: 'opentts' | 'openai' | 'mms'
# opentts: uses voice
# openai:  uses model + voice
# mms:     uses model

# Diana
protocol = "opentts"
api_base = "http://opentts:5500/api/tts"
voice = "hu_diana_majlinger"

# Facebook english
#protocol = "mms"
#model = "facebook/mms-tts-eng"

#protocol = "openai"
#api_base = "http://10.6.6.20:8880/v1"
#voice = "alloy"
#model = "tts-1"

#- TTS_VOICE=larynx:eva_k-glow_tts
#- TTS_VOICE=hu_diana_majlinger
#- TTS_VOICE=zh_baker
#- TTS_ENGINE_API=http://10.6.6.20:8124/synthesize/

[ports]
voice = 5052
control = 5002
