services:
  onboard:
    build: .
    container_name: onboard
    devices:
      - "/dev/video4:/dev/video4"
      - "/dev/serial0:/dev/serial0"
    network_mode: host        
    environment:
      - VIDEO_DST=10.6.6.20
      - VIDEO_PORT=5100
