[supervisord]
nodaemon=true

[program:streamer]
#command=tmux new-session -d -s streamer 'uv run --with-requirements /root/camera/requirements.txt python3 /root/camera/main.py --config /root/streamer.cfg; sleep inf'
command=uv run --with-requirements /root/camera/requirements.txt python3 /root/camera/main.py --config /root/streamer.cfg
autostart=true
autorestart=true
#stderr_logfile=/var/log/streamer.err.log
#stdout_logfile=/var/log/streamer.out.log
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

environment=PYTHONUNBUFFERED=1


[program:socat0]
command=socat -d -d TCP4-LISTEN:54321,reuseaddr,fork file:/dev/serial0,b115200,raw,echo=0
autostart=true
autorestart=true
stderr_logfile=/var/log/socat0.err.log
stdout_logfile=/var/log/socat0.out.log