[supervisord]
nodaemon=true

[program:streamer]
command=bash -c "uv run --with-requirements /root/streamer/requirements.txt python3 /root/streamer/main.py --config /root/streamer.cfg | sed 's/^/[STREAMER] /'"
autostart=true
autorestart=true
#stderr_logfile=/var/log/streamer.err.log
#stdout_logfile=/var/log/streamer.out.log
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
#stderr_logfile=/dev/stderr
#stderr_logfile_maxbytes=0
environment=PYTHONUNBUFFERED=1

#[program:socat0]
#command=socat -d -d TCP4-LISTEN:54321,reuseaddr,fork file:/dev/serial0,b115200,raw,echo=0
#autostart=true
#autorestart=true
#stderr_logfile=/var/log/socat0.err.log
#stdout_logfile=/var/log/socat0.out.log

[program:socat0]
command=socat -d -d PTY,link=/dev/serial0,raw,echo=0 PTY,raw,echo=0
autostart=true
autorestart=true
#stderr_logfile=/var/log/socat0.err.log
#stdout_logfile=/var/log/socat0.out.log


[program:dogzillalib_api]
command=bsh -c "python3 -m DOGZILLALib.DOGZILLALibAPI  --serial-port %(SERIAL_PORT)s | sed 's/^/[DOGZILLA] /'"
directory=/root
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
#stderr_logfile=/dev/stderr
#stderr_logfile_maxbytes=0
environment=PYTHONPATH="/root",PYTHONUNBUFFERED=1
