[pupcard]
language = "ENG"
model = "Nemotron 3 ULTRA"
tts = "Meta ENG"

[general]
cache = "~/.cache/jensen"
log = "~/log/jensen"

[language]
ui = "en"
prompt = "en"

[models]
general = "nvidia/nemotron-3-ultra-550b-a55b"
translation = ""
vision = ""

[openai]
api_base = "https://integrate.api.nvidia.com/v1"
api_key = "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"
keep_alive = "30m"
scheme = "nim"
enable_thinking = true
thinking_budget = 16384
max_output_tokens = 16384
translation_max_output_tokens = 2048
prompt_temperature = 1
prompt_frequency_penalty = 0.8
binary_images = false

[tts]
# Facebook english
protocol = "mms"
model = "facebook/mms-tts-eng"

[ports]
voice = 5059
control = 5002

[streamer]
url = "http://10.100.0.38:8000"
stream_ip = "10.100.0.20"
stream_port = 5100

[tools]
list = ["highfive", "dice", "body", "visionprompt"]

[skills]
list = ["cautious_navigation", "object_search", "visual_vlm_analysis"]
