services:
  control:
    build: .
    container_name: dogi
    #network_mode: host
    environment:
      - DISPLAY=:0
      #- ROBOT_IP=192.168.1.140
      - ROBOT_IP=10.20.5.2
      - OLLAMA_IP=10.6.6.20
      - TTS_IP=opentts
    ports:
      - "6080:6080"
      - "5050-5059:5050-5059"
      - "5100:5100/udp"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    #command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
    #command: ["/bin/sh", "-c", "sleep inf"]

  opentts:
    image: synesthesiam/opentts:hu
    container_name: opentts
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
