services:
  control:
    build: .
    container_name: control
    #network_mode: host
    environment:
      - DISPLAY=:0
      - ROBOT_IP=192.168.1.140
      #- ROBOT_IP=10.20.11.49
    ports:
      - "6080:6080"
      - "5100:5100/udp"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
