services:

  dogi-base:
    profiles:
      - build
    build:
      context: .
      dockerfile: Dockerfile.base
    image: dogi-base:latest # Ezt a nevet fogja kapni az image


  control:
    build: .
    container_name: dogi
    #network_mode: host
    environment:
      #- DEBUG=1  # Fake images in "keresd"
      - DISPLAY=:0
      - ROBOT_IP=192.168.1.248
      #- ROBOT_IP=10.20.5.38
    ports:
      - "6080:6080"
      - "5050-5059:5050-5059"
      - "5100:5100/udp"
    volumes:
      - ./Ultralytics:/root/.config/Ultralytics:rw
      - ./cache/huggingface:/root/.cache/huggingface:rw
      - ./cache/voice:/root/.cache/voice:rw
      - ./cache/debug:/tmp/debug:ro
      - ./yolov8m-seg.pt:/root/yolov8m-seg.pt
      - ./config:/config
      - ./src:/app:ro
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]

  opentts:
    image: synesthesiam/opentts:hu
    #image: synesthesiam/opentts:de
    #image: synesthesiam/opentts:zh
    container_name: opentts
    ports:
       - "5500:5500"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
