services:

  dogi-base:
    profiles:
      - base
    build:
      context: .
      dockerfile: Dockerfile.base
    image: dogi-base:latest # Ezt a nevet fogja kapni az image


  control:
    build: .
    container_name: dogi
    #network_mode: host
    environment:
      #- DEBUG=1  # Fake images in "keresd"
      - DISPLAY=:0
      #- ROBOT_IP=192.168.1.248 # WiFi address
      #- ROBOT_IP=10.20.5.38  # 5G address
      - ROBOT_IP=10.100.0.38  # Wireguard address
      - DOGZILLA_API_BASE=http://10.100.0.38:8001
      - VICTORIA_BASE_URL=http://dogi-vm:8428
      - PHOENIX_COLLECTOR_ENDPOINT=http://dogi-phoenix:6006
      - MCP_KEY=${MCP_KEY}
      #- HF_HUB_OFFLINE=1
      #- TRANSFORMERS_OFFLINE=1
    ports:
      #- "6080:6080" # the remote display port
      #- "5050-5059:5050-5059"
      - "5100:5100/udp" # the incoming video port
    volumes:
      - ./Ultralytics:/root/.config/Ultralytics:rw
      - ./cache/huggingface:/root/.cache/huggingface:rw
      - ./cache/voice:/root/.cache/voice:rw
      - ./cache/debug:/tmp/debug:ro
      - ./yolov8m-seg.pt:/root/yolov8m-seg.pt
      - ./config:/config
      - ./src:/app:ro
      - ./id_ed25519:/root/.ssh/id_ed25519:ro
      - ./id_ed25519.pub:/root/.ssh/id_ed25519.pub:ro
      - ./log:/root/log
      #- /tmp/dogi:/tmp
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]

  cloud-mcp:
    build:
      context: mcp
      dockerfile: Dockerfile
    container_name: dogi-mcp
    environment:
      - MCP_KEY=${MCP_KEY}
      - VP_CONFIG=/config/vp_config.toml
    ports:
      - "5000:5000"
    volumes:
      - ./mcp/vp_config.toml:/config/vp_config.toml:ro
    restart: unless-stopped

  opentts:
    image: synesthesiam/opentts:hu
    #image: synesthesiam/opentts:de
    #image: synesthesiam/opentts:zh
    container_name: opentts
    ports:
       - "5500:5500"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]

  victoriametrics:
    image: victoriametrics/victoria-metrics:latest
    container_name: dogi-vm
    expose:
      - 8428
    volumes:
      # PERSISTENCE: This ensures your data survives container restarts/updates
      - ./vmdata:/storage
    command:
      - "--storageDataPath=/storage"
    restart: unless-stopped

  phoenix:
    image: arizephoenix/phoenix:latest
    container_name: dogi-phoenix
    ports:
      - "6006:6006"  # UI and OTLP HTTP collector
      - "4317:4317"  # OTLP gRPC collector

  caddy:
    image: caddy:2-alpine
    container_name: dogi-proxy
    ports:
      - "5059:5059"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config