[pupcard]
language = "ENG"
model = "Nemotron 3"
tts = "Meta ENG"

[general]
cache = "~/.cache/spike"
log = "~/log/spike"

[language]
ui = "en"
prompt = "en"

[models]
general = "nemotron-3-nano:4b"
translation = ""
vision = ""

[tools]
# ssh for stdio MCP servers
# sse for SSE MCP servers
# str for Streamable HTTP MCP servers
highfive = "ssh!robot@10.6.6.20:~/kutyus_env/bin:~/mcptest/server.py"
#capture = "sse!http://robot_ip:8000/mcp/sse"
dice = "ssh!robot@10.6.6.20:~/kutyus_env/bin:~/mcptest/mcpserver_dice.py"
body = "str!http://robot_ip:5000/mcp"
visionprompt = "str!http://dogi-mcp:5000/mcp"

[openai]
api_base = "http://10.6.6.20:11434/v1"
api_key = "not-needed"
keep_alive = "30m"
enable_thinking = true
thinking_budget = 1024
max_output_tokens = 1536
translation_max_output_tokens = 2048
prompt_temperature = 0.9
prompt_frequency_penalty = 0.8
binary_images = false

[tts]
# Facebook english
protocol = "mms"
model = "facebook/mms-tts-eng"

[ports]
voice = 5059
control = 5002

[streamer]
url = "http://10.100.0.38:8000"
stream_ip = "10.100.0.20"
stream_port = 5100
