[pupcard]
language = "ENG"
model = "lfm2.5:1.2b + Qwen3-VL:4b"
#model = "phi4-mini"
tts = "Meta ENG"

[general]
cache = "~/.cache/chewie"
log = "~/log/chewie"

[language]
ui = "en"
prompt = "en"

[models]
general = "lfm2.5-thinking:1.2b"
#general = "phi4-mini:latest"
translation = ""
vision = "qwen3-vl:4b"

[openai]
api_base = "http://10.6.6.20:11434/v1"
api_key = "not-needed"
keep_alive = "30m"
enable_thinking = false
thinking_budget = 1024
max_output_tokens = 1536
translation_max_output_tokens = 2048
prompt_temperature = 0.9
prompt_frequency_penalty = 0.8
binary_images = false
ollama = true

[tts]
protocol = "opentts"
api_base = "http://opentts:5500/api/tts"
voice = "coqui-tts:en_ljspeech"

[ports]
voice = 5059
control = 5002

[streamer]
url = "http://10.100.0.38:8000"
stream_ip = "10.100.0.20"
stream_port = 5100

[tools]
list = ["highfive", "dice", "body", "visionprompt"]

[skills]
list = ["cautious_navigation", "object_search", "visual_vlm_analysis"]
