[pupcard]
language = "HUN"
model = "Qwen3.5"
tts = "TTS:HUN Diana"

[general]
cache = "~/.cache/bodrika"
log = "~/log/bodrika"

[language]
ui = "hu"
prompt = "hu"

[models]
general = "qwen3.5:4B"
translation = ""
vision = ""

[tools]
# ssh for stdio MCP servers
# sse for SSE MCP servers
# str for Streamable HTTP MCP servers
highfive = "ssh!robot@10.6.6.20:~/kutyus_env/bin:~/mcptest/server.py"
#capture = "sse!http://robot_ip:8000/mcp/sse"
dice = "ssh!robot@10.6.6.20:~/kutyus_env/bin:~/mcptest/mcpserver_dice.py"
body = "str!http://robot_ip:5000/mcp"
visionprompt = "str!http://dogi-mcp:5000/mcp"

[openai]
api_base = "http://10.6.6.20:11434/v1"
api_key = "not-needed"
keep_alive = "30m"
enable_thinking = false
thinking_budget = 1024
max_output_tokens = 1536
translation_max_output_tokens = 2048
prompt_temperature = 0.9
prompt_frequency_penalty = 1.5
binary_images = false

[tts]
# TTS protocol: 'opentts' | 'openai' | 'mms'
# opentts: uses voice
# openai:  uses model + voice
# mms:     uses model

# Diana
protocol = "opentts"
api_base = "http://opentts:5500/api/tts"
voice = "hu_diana_majlinger"

# Facebook english
#protocol = "mms"
#model = "facebook/mms-tts-eng"

#protocol = "openai"
#api_base = "http://10.6.6.20:8880/v1"
#voice = "alloy"
#model = "tts-1"

#- TTS_VOICE="larynx:eva_k-glow_tts"
#- TTS_VOICE="hu_diana_majlinger"
#- TTS_VOICE="zh_baker"
#- TTS_ENGINE_API="http://10.6.6.20:8124/synthesize/"

[ports]
voice = 5059
control = 5002

[streamer]
url = "http://10.100.0.38:8000"
stream_ip = "10.100.0.20"
stream_port = 5100
